# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 5) do

  create_table "actuals", :force => true do |t|
    t.column "text",        :string
    t.column "visible",     :boolean
    t.column "create_date", :datetime
    t.column "position",    :integer,  :default => 100, :null => false
  end

  create_table "languages", :force => true do |t|
    t.column "language_name", :string, :limit => nil
  end

  create_table "test_pages", :force => true do |t|
    t.column "language_id",  :integer,  :default => 1,     :null => false
    t.column "author",       :string,                      :null => false
    t.column "name",         :string,                      :null => false
    t.column "description",  :string,                      :null => false
    t.column "top_text",     :string,                      :null => false
    t.column "test_text",    :string,                      :null => false
    t.column "create_date",  :datetime
    t.column "modify_date",  :datetime
    t.column "deleted",      :boolean,  :default => false, :null => false
    t.column "test_type_id", :integer,  :default => 1,     :null => false
    t.column "position",     :integer,  :default => 100,   :null => false
  end

  create_table "test_types", :force => true do |t|
    t.column "name", :string, :null => false
  end

end
